# SwiftLint Configuration for Toboggan Project

# File patterns to include
included:
  - toboggan-ios

# File patterns to exclude
excluded:
  - toboggan-ios/target
  - toboggan-ios/.build
  - toboggan-ios/build
  - toboggan-ios/TobogganApp.xcodeproj
  - toboggan-ios/TobogganApp.xcworkspace

# Rules to disable
disabled_rules:
  - trailing_whitespace # Handled by other formatters

# Rules to enable (opt-in rules)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Line length configuration
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# Function body length
function_body_length:
  warning: 60
  error: 100

# Function parameter count
function_parameter_count:
  warning: 8
  error: 10

# Type body length
type_body_length:
  warning: 300
  error: 400

# File length
file_length:
  warning: 400
  error: 500

# Type name configuration
type_name:
  min_length: 2
  max_length: 40

# Identifier name configuration
identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - to
    - vm

# Nesting configuration
nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 5
    error: 7

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 15

# Force unwrapping configuration
force_unwrapping:
  severity: warning

# Reporter configuration (for CI/CD)
reporter: "github-actions-logging"