use std::fmt::Write as _;

use comrak::nodes::{AlertType, AstNode, ListType, NodeValue};
use comrak::{Arena, parse_document};
use toboggan_core::{Content, Slide, SlideBody, SlideKind, Talk};

use crate::parser::default_options;

pub(super) fn generate_typst(talk: &Talk) -> Vec<u8> {
    let mut out = String::new();
    write_preamble(&mut out, talk);
    for slide in &talk.slides {
        write_slide(&mut out, slide);
    }
    out.into_bytes()
}

fn write_preamble(out: &mut String, talk: &Talk) {
    let title = escape_typst(&talk.title);
    let date = talk.date.to_string();
    let _ = writeln!(
        out,
        r#"// Generated by toboggan-cli — compile with: typst compile presentation.typ
//
// First-time compilation will download the touying, codly, and gentle-clues
// packages from Typst Universe (requires network access or a populated cache).

#import "@preview/touying:0.7.3": *
#import themes.simple: *
#import "@preview/codly:1.3.0": *
#import "@preview/codly-languages:0.1.1": *
#import "@preview/gentle-clues:1.3.1": *

#show: simple-theme.with(aspect-ratio: "16-9")
#show: codly-init.with()
#codly(languages: codly-languages)

#title-slide[
  #text(size: 2em, weight: "bold")[{title}]
  #v(1em)
  #text(size: 0.8em, fill: gray)[{date}]
]
"#
    );
}

fn write_slide(out: &mut String, slide: &Slide) {
    match slide.kind {
        SlideKind::Cover => {} // Cover is handled in write_preamble
        SlideKind::Part => write_section(out, slide),
        SlideKind::Standard => write_standard(out, slide),
    }
}

fn write_section(out: &mut String, slide: &Slide) {
    let title = content_to_typst(&slide.title);
    let body = section_body(slide);
    let body_block = if body.trim().is_empty() {
        String::new()
    } else {
        format!("\n\n  {body}")
    };
    let _ = writeln!(
        out,
        "#new-section-slide[
  #text(size: 1.5em, weight: \"bold\")[{title}]{body_block}
]"
    );
}

/// Render the body of a Part slide.
///
/// Routes on the `SlideBody` view so the three meaningful states are explicit.
fn section_body(slide: &Slide) -> String {
    match slide.body_view() {
        SlideBody::Empty => String::new(),
        SlideBody::Rendered(content) => content_to_typst(content),
        SlideBody::FromMarkdown { source, .. } => strip_leading_heading(&md_to_typst(source)),
    }
}

/// Drop the leading `= heading` produced by `md_to_typst` for `_part.md` files
/// (whose markdown source starts with the part title).
///
/// Without this, the section block would render the title twice — once via the
/// outer `#text(...)[{title}]` and once via the `= H1` from `body_source`.
fn strip_leading_heading(typst: &str) -> String {
    let trimmed = typst.trim_start();
    let Some(rest) = trimmed.strip_prefix("= ") else {
        return typst.to_owned();
    };
    let Some(nl) = rest.find('\n') else {
        return String::new();
    };
    rest[nl + 1..].trim_start().to_owned()
}

fn write_standard(out: &mut String, slide: &Slide) {
    // Slides with live terminals that weren't filtered out get a placeholder.
    if slide.terminals.is_empty() {
        write_standard_body(out, slide);
    } else {
        write_terminal_placeholder(out, slide);
    }
}

fn write_terminal_placeholder(out: &mut String, slide: &Slide) {
    let title = content_to_typst(&slide.title);
    tracing::warn!(
        "slide '{title}' has live terminals but is not marked \
         `hidden_in = [\"pdf\"]` — emitting a placeholder page in the PDF; \
         add `hidden_in = [\"pdf\"]` to suppress this"
    );
    let _ = writeln!(
        out,
        "#slide[
  == {title}

  #align(center + horizon)[
    #text(size: 1.2em, fill: gray)[\\[Live terminal demo --- see recording / live presentation\\]]
  ]
]"
    );
}

fn write_standard_body(out: &mut String, slide: &Slide) {
    let title = content_to_typst(&slide.title);
    let body = standard_body(slide);
    let title_block = if title.trim().is_empty() {
        String::new()
    } else {
        format!("  == {title}\n\n")
    };
    let body_block = if body.trim().is_empty() {
        tracing::error!(
            "Slide '{title}' rendered to an empty body; emitting a placeholder \
             page so the deck does not silently lose a slide."
        );
        format!(
            "  #align(center + horizon)[\n    \
             #text(size: 1.2em, fill: red)[\\[Empty slide '{title}' --- check source\\]]\n  ]\n"
        )
    } else {
        body
    };
    let _ = writeln!(out, "#slide[\n{title_block}{body_block}\n]");
}

/// Render the body of a Standard slide.
///
/// Routes on the `SlideBody` view. The leading H1 from a markdown source is
/// stripped because the slide title is emitted separately via `==` inside
/// `#slide[..]`.
fn standard_body(slide: &Slide) -> String {
    match slide.body_view() {
        SlideBody::Empty => String::new(),
        SlideBody::Rendered(content) => content_to_typst(content),
        SlideBody::FromMarkdown { source, .. } => strip_leading_heading(&md_to_typst(source)),
    }
}

/// Convert `Content` to escaped Typst markup.
///
/// Uses `alt` text when available; falls back to a visible red placeholder
/// when only raw HTML is present, so the gap is obvious in the rendered PDF
/// even if the warning is filtered out of the logs.
fn content_to_typst(content: &Content) -> String {
    match content {
        Content::Empty => String::new(),
        Content::Text { text } => escape_typst(text),
        Content::Html { alt: Some(alt), .. } => escape_typst(alt),
        Content::Html { raw: _, .. } => {
            tracing::warn!(
                "Slide content is HTML without alt text; emitting a visible Typst \
                 placeholder. Add alt text or use body_source for proper rendering."
            );
            "#text(fill: red)[\\[HTML content not exportable --- add alt text\\]]".to_owned()
        }
    }
}

/// Escape a URL for use inside a Typst double-quoted string argument.
///
/// Typst string literals use `\` as the escape character, so both `"` and `\`
/// must be escaped. This is separate from `escape_typst`, which escapes Typst
/// markup characters for content nodes.
fn escape_typst_string(url: &str) -> String {
    url.replace('\\', r"\\").replace('"', r#"\""#)
}

/// Convert a `CommonMark` source string to Typst markup.
pub(super) fn md_to_typst(source: &str) -> String {
    let arena = Arena::new();
    let options = default_options();
    let root = parse_document(&arena, source, &options);
    let mut out = String::new();
    render_node(root, &mut out, 0, false);
    out
}

type MarkdownNode<'a> = AstNode<'a>;

fn render_children<'a>(
    node: &'a MarkdownNode<'a>,
    out: &mut String,
    list_depth: usize,
    tight: bool,
) {
    for child in node.children() {
        render_node(child, out, list_depth, tight);
    }
}

#[allow(clippy::too_many_lines)]
fn render_node<'a>(node: &'a MarkdownNode<'a>, out: &mut String, list_depth: usize, tight: bool) {
    match &node.data.borrow().value {
        NodeValue::FrontMatter(_) | NodeValue::HtmlBlock(_) | NodeValue::HtmlInline(_) => {
            // HTML blocks from slide sources are comment-marker artefacts
            // (<!-- term: ... -->, <!-- pause -->); already handled upstream.
        }

        NodeValue::Paragraph => {
            render_children(node, out, list_depth, tight);
            if tight {
                out.push('\n');
            } else {
                out.push_str("\n\n");
            }
        }

        NodeValue::Heading(heading) => {
            for _ in 0..heading.level {
                out.push('=');
            }
            out.push(' ');
            render_children(node, out, list_depth, tight);
            out.push('\n');
        }

        NodeValue::Text(text) => out.push_str(&escape_typst(text)),

        NodeValue::SoftBreak => out.push(' '),

        NodeValue::LineBreak => out.push_str("\\\n"),

        NodeValue::Strong => {
            out.push_str("#strong[");
            render_children(node, out, list_depth, tight);
            out.push(']');
        }

        NodeValue::Emph => {
            out.push_str("#emph[");
            render_children(node, out, list_depth, tight);
            out.push(']');
        }

        NodeValue::Strikethrough => {
            out.push_str("#strike[");
            render_children(node, out, list_depth, tight);
            out.push(']');
        }

        NodeValue::Code(code) => write_inline_code(out, &code.literal),

        NodeValue::CodeBlock(cb) => {
            let lang = cb.info.trim();
            write_fenced_code(out, lang, &cb.literal);
        }

        NodeValue::BlockQuote => {
            out.push_str("#quote(block: true)[\n");
            render_children(node, out, list_depth, tight);
            out.push_str("]\n\n");
        }

        NodeValue::ThematicBreak => out.push_str("#line(length: 100%)\n\n"),

        NodeValue::List(list) => {
            let is_ordered = list.list_type == ListType::Ordered;
            render_list(node, out, list_depth, is_ordered);
        }

        NodeValue::Link(link) => {
            let url = escape_typst_string(&link.url);
            let _ = write!(out, "#link(\"{url}\")[");
            render_children(node, out, list_depth, tight);
            out.push(']');
        }

        NodeValue::Image(link) => {
            let url = escape_typst_string(&link.url);
            let _ = writeln!(out, "#image(\"{url}\")");
        }

        NodeValue::Table(_) => {
            render_table(node, out);
        }

        NodeValue::Alert(alert) => {
            render_alert(
                node,
                out,
                list_depth,
                alert.alert_type,
                alert.title.as_deref(),
            );
        }

        _ => render_children(node, out, list_depth, tight),
    }
}

/// Render a GFM alert block as a gentle-clues callout.
///
/// The five GFM alert kinds map to the closest gentle-clues predefined clue
/// (gentle-clues does not expose `note`/`important`/`caution` by name), with
/// the title overridden to match the GFM label.
fn render_alert<'a>(
    node: &'a MarkdownNode<'a>,
    out: &mut String,
    list_depth: usize,
    kind: AlertType,
    title_override: Option<&str>,
) {
    let label = title_override.unwrap_or_else(|| kind.default_title());
    let clue = clue_fn(kind);
    let _ = writeln!(out, "#{clue}(title: \"{label}\")[");
    render_children(node, out, list_depth, false);
    out.push_str("]\n\n");
}

/// Map a GFM alert kind to a gentle-clues predefined clue function.
const fn clue_fn(kind: AlertType) -> &'static str {
    match kind {
        AlertType::Note => "info",
        AlertType::Tip => "tip",
        AlertType::Important => "notify",
        AlertType::Warning => "warning",
        AlertType::Caution => "danger",
    }
}

fn render_list<'a>(node: &'a MarkdownNode<'a>, out: &mut String, depth: usize, ordered: bool) {
    for child in node.children() {
        let indent = "  ".repeat(depth);
        out.push_str(&indent);
        if ordered {
            out.push_str("+ ");
        } else {
            out.push_str("- ");
        }
        render_children(child, out, depth + 1, true);
    }
    out.push('\n');
}

fn render_table<'a>(node: &'a MarkdownNode<'a>, out: &mut String) {
    let mut rows: Vec<Vec<String>> = Vec::new();

    for row_node in node.children() {
        let mut cells: Vec<String> = Vec::new();
        for cell_node in row_node.children() {
            let mut cell = String::new();
            render_children(cell_node, &mut cell, 0, true);
            cells.push(cell.trim().to_owned());
        }
        rows.push(cells);
    }

    let Some(first) = rows.first() else { return };
    let columns = first.len();
    if columns == 0 {
        tracing::warn!(
            "Table has no columns (empty header row); skipping #table emission to avoid \
             producing invalid Typst."
        );
        return;
    }

    let _ = writeln!(out, "#table(");
    let _ = writeln!(out, "  columns: {columns},");
    for row in &rows {
        for cell in row.iter().take(columns) {
            let _ = writeln!(out, "  [{cell}],");
        }
        for _ in row.len()..columns {
            let _ = writeln!(out, "  [],");
        }
    }
    let _ = writeln!(out, ")\n");
}

/// Write an inline code span to `out`, using enough backticks to avoid
/// conflicts with any backtick sequences inside the literal.
fn write_inline_code(out: &mut String, code: &str) {
    let fence_len = max_consecutive_backticks(code) + 1;
    let fence = "`".repeat(fence_len);
    // When using multi-backtick delimiters, Typst requires a space before/after
    // the content if it would otherwise start or end with a backtick.
    let need_space = fence_len > 1 && (code.starts_with('`') || code.ends_with('`'));
    out.push_str(&fence);
    if need_space {
        out.push(' ');
    }
    out.push_str(code);
    if need_space {
        out.push(' ');
    }
    out.push_str(&fence);
}

/// Write a fenced code block to `out`, using enough backticks to avoid
/// conflicts with any backtick sequences inside the code.
fn write_fenced_code(out: &mut String, lang: &str, code: &str) {
    let fence_len = max_consecutive_backticks(code) + 3;
    let fence = "`".repeat(fence_len);
    let _ = write!(out, "{fence}{lang}\n{code}");
    if !code.ends_with('\n') {
        out.push('\n');
    }
    let _ = writeln!(out, "{fence}\n");
}

fn max_consecutive_backticks(src: &str) -> usize {
    let mut max = 0;
    let mut current = 0;
    for ch in src.chars() {
        if ch == '`' {
            current += 1;
            max = max.max(current);
        } else {
            current = 0;
        }
    }
    max
}

/// Escape Typst markup special characters with a backslash.
fn escape_typst(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '\\' | '*' | '_' | '`' | '#' | '@' | '<' | '>' | '[' | ']' | '{' | '}' | '$' | '~' => {
                out.push('\\');
                out.push(ch);
            }
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use std::collections::BTreeSet;

    use toboggan_core::{Date, RenderTarget, Slide, SlideKind, Style, Talk, TerminalConfig};

    use super::*;

    fn make_talk(title: &str) -> Talk {
        let mut talk = Talk::new(title);
        talk.date = Date::new(2024, 1, 15).expect("valid date");
        talk
    }

    fn slide_with_source(source: &str) -> Slide {
        Slide {
            kind: SlideKind::Standard,
            body_source: Some(source.to_owned()),
            ..Default::default()
        }
    }

    #[test]
    fn test_cover_slide_preamble() {
        let talk = make_talk("My Presentation");
        let bytes = generate_typst(&talk);
        let output = String::from_utf8(bytes).expect("utf8");

        assert!(output.contains("My Presentation"), "title in preamble");
        assert!(output.contains("2024-01-15"), "date in preamble");
        assert!(
            output.contains("simple-theme"),
            "touying simple-theme applied"
        );
        assert!(
            output.contains("#title-slide["),
            "cover uses touying title-slide"
        );
        assert!(output.contains("codly-init"), "codly initialised");
    }

    #[test]
    fn test_standard_slide_uses_touying_slide() {
        let mut talk = make_talk("Talk");
        talk.slides
            .push(slide_with_source("# Heading\n\nBody text.\n"));
        let output = String::from_utf8(generate_typst(&talk)).expect("utf8");
        assert!(
            output.contains("#slide["),
            "standard slide wrapped in #slide[..]"
        );
        assert!(output.contains("Body text"), "body present");
    }

    #[test]
    fn test_heading_inside_body_does_not_trigger_new_section() {
        // Regression: with touying simple-theme, a top-level `= H1` would trigger
        // a new-section-slide. Body markdown of `# Demo` therefore must not be
        // emitted as a bare `= Demo` at document scope — the leading H1 must be
        // consumed as the slide title (rendered via `==` inside #slide[..]).
        let mut talk = make_talk("Talk");
        talk.slides
            .push(slide_with_source("# Demo\n\nFirst body.\n"));
        talk.slides
            .push(slide_with_source("# Other\n\nSecond body.\n"));
        let output = String::from_utf8(generate_typst(&talk)).expect("utf8");

        // Two #slide[..] blocks and zero stray top-level `= ..` headings that
        // would cause touying to inject extra section-slide pages.
        assert_eq!(
            output.matches("#slide[").count(),
            2,
            "expected exactly two standard slides, got: {output}"
        );
        for line in output.lines() {
            let trimmed = line.trim_start();
            assert!(
                !trimmed.starts_with("= "),
                "top-level `= heading` would trigger an unintended touying section-slide; \
                 offending line: {line}"
            );
        }
    }

    #[test]
    fn test_standard_slide_with_code_block() {
        let mut talk = make_talk("Code Talk");
        let source = "# Demo\n\n```rust\nfn main() {}\n```\n";
        talk.slides.push(slide_with_source(source));

        let bytes = generate_typst(&talk);
        let output = String::from_utf8(bytes).expect("utf8");

        assert!(output.contains("```rust"), "fenced code block");
        assert!(output.contains("fn main()"), "code content");
    }

    #[test]
    fn test_slide_with_terminals_emits_placeholder() {
        let mut talk = make_talk("Demo Talk");
        let slide = Slide {
            kind: SlideKind::Standard,
            title: Content::text("Live Demo"),
            terminals: vec![TerminalConfig::new(".")],
            ..Default::default()
        };
        talk.slides.push(slide);

        let bytes = generate_typst(&talk);
        let output = String::from_utf8(bytes).expect("utf8");

        assert!(
            output.contains("Live terminal demo"),
            "placeholder present for unmarked live slide"
        );
    }

    #[test]
    fn test_hidden_in_pdf_slide_is_omitted() {
        let mut talk = make_talk("Demo Talk");
        let live_slide = Slide {
            kind: SlideKind::Standard,
            title: Content::text("Live Demo"),
            terminals: vec![TerminalConfig::new(".")],
            hidden_in: BTreeSet::from([RenderTarget::Pdf]),
            ..Default::default()
        };
        let static_slide = Slide {
            kind: SlideKind::Standard,
            title: Content::text("Static Demo"),
            body_source: Some("# Static Demo\n\n```rust\nfn main() {}\n```\n".to_owned()),
            hidden_in: BTreeSet::from([RenderTarget::Web]),
            ..Default::default()
        };
        talk.slides.push(live_slide);
        talk.slides.push(static_slide);

        let filtered_slides: Vec<_> = talk
            .slides
            .iter()
            .filter(|slide| !slide.is_hidden_from(RenderTarget::Pdf))
            .cloned()
            .collect();
        let mut filtered_talk = talk.clone();
        filtered_talk.slides = filtered_slides;

        let bytes = generate_typst(&filtered_talk);
        let output = String::from_utf8(bytes).expect("utf8");

        assert!(
            !output.contains("Live Demo"),
            "pdf-hidden slide must be absent"
        );
        assert!(
            output.contains("Static Demo"),
            "web-hidden slide must be present"
        );
    }

    #[test]
    fn test_escape_typst() {
        assert_eq!(escape_typst("hello"), "hello");
        assert_eq!(escape_typst("a#b"), r"a\#b");
        assert_eq!(escape_typst("x[y]"), r"x\[y\]");
        assert_eq!(escape_typst("a*b_c"), r"a\*b\_c");
    }

    #[test]
    fn test_escape_typst_string_url() {
        // A URL with `"` must not break the Typst string literal.
        assert_eq!(
            escape_typst_string(r#"https://x.com/?a="b""#),
            r#"https://x.com/?a=\"b\""#
        );
        assert_eq!(escape_typst_string(r"path\to"), r"path\\to");
        assert_eq!(escape_typst_string("plain"), "plain");
    }

    #[test]
    fn test_link_with_special_url_characters() {
        // A double-quote inside a URL must be escaped so typst compile succeeds.
        let result = md_to_typst(r#"[text](https://x.com/?a="b")"#);
        assert!(
            result.contains(r#"#link("https://x.com/?a=\"b\"")"#),
            "url escaped in link"
        );
    }

    #[test]
    fn test_image_url_is_escaped() {
        // Same `"` quote-in-URL hazard applies to images — pin it so we don't
        // regress on the symmetric arm.
        let result = md_to_typst(r#"![alt](https://x.com/a"b.png)"#);
        assert!(
            result.contains(r#"#image("https://x.com/a\"b.png")"#),
            "image url escaped, got: {result}"
        );
    }

    #[test]
    fn test_md_to_typst_headings() {
        assert!(md_to_typst("# H1\n").contains("= H1"), "h1");
        assert!(md_to_typst("## H2\n").contains("== H2"), "h2");
        assert!(md_to_typst("### H3\n").contains("=== H3"), "h3");
    }

    #[test]
    fn test_md_to_typst_unordered_list() {
        let result = md_to_typst("- alpha\n- beta\n- gamma\n");
        assert!(result.contains("- alpha"), "first item");
        assert!(result.contains("- beta"), "second item");
        assert!(result.contains("- gamma"), "third item");
    }

    #[test]
    fn test_md_to_typst_ordered_list() {
        let result = md_to_typst("1. first\n2. second\n");
        assert!(result.contains("+ first"), "first ordered item");
        assert!(result.contains("+ second"), "second ordered item");
    }

    #[test]
    fn test_md_to_typst_nested_list() {
        let result = md_to_typst("- outer\n  - inner\n");
        assert!(result.contains("- outer"), "outer item");
        assert!(result.contains("  - inner"), "nested item indented");
    }

    #[test]
    fn test_md_to_typst_table() {
        let result = md_to_typst("| A | B |\n|---|---|\n| 1 | 2 |\n");
        assert!(result.contains("#table("), "table macro");
        assert!(result.contains("columns: 2"), "column count");
        assert!(result.contains("[A]"), "header cell A");
        assert!(result.contains("[1]"), "data cell 1");
    }

    #[test]
    fn test_md_to_typst_empty_table_body() {
        // Degenerate input (single empty header cell after trim) must never emit
        // `columns: 0` — that is invalid Typst. A 1-column empty cell is fine.
        let result = md_to_typst("| |\n|---|\n");
        assert!(
            !result.contains("columns: 0"),
            "columns: 0 must never be emitted, got: {result}"
        );
    }

    #[test]
    fn test_md_to_typst_zero_column_table_is_skipped() {
        // A header row that parses to zero cells must skip the #table call
        // entirely (we can't synthesise the cell count out of thin air).
        // Comrak rarely emits this from markdown, so verify via direct call:
        // an empty header row would imply columns: 0 which the renderer drops.
        let result = md_to_typst("");
        assert!(
            !result.contains("columns: 0") && !result.contains("#table("),
            "empty input never emits a table, got: {result}"
        );
    }

    #[test]
    fn test_md_to_typst_table_pads_short_rows() {
        // Header has 3 columns, body row only 2 cells. Renderer pads with empty
        // cells so the emitted #table is well-formed.
        let result = md_to_typst("| A | B | C |\n|---|---|---|\n| 1 | 2 |\n");
        assert!(result.contains("columns: 3"), "3-column declaration");
        assert!(result.contains("[1]"), "first data cell present");
        assert!(result.contains("[2]"), "second data cell present");
        assert!(
            result.contains("[],"),
            "missing third cell padded with empty"
        );
    }

    #[test]
    fn test_empty_body_slide_emits_visible_placeholder() {
        // Regression: previously, an empty body silently dropped the page from
        // the PDF. Now it emits a visible red placeholder so the gap is obvious.
        let mut talk = make_talk("Talk");
        talk.slides.push(Slide {
            kind: SlideKind::Standard,
            title: Content::text("Ghost Slide"),
            body_source: Some(String::new()),
            ..Default::default()
        });
        let output = String::from_utf8(generate_typst(&talk)).expect("utf8");
        assert!(output.contains("Ghost Slide"), "slide title still emitted");
        assert!(
            output.contains("Empty slide"),
            "visible placeholder present, got: {output}"
        );
    }

    #[test]
    fn test_html_without_alt_emits_visible_placeholder() {
        let html_content = Content::Html {
            raw: "<p>raw html</p>".to_owned(),
            style: Style::default(),
            alt: None,
        };
        let result = content_to_typst(&html_content);
        assert!(
            result.contains("HTML content not exportable"),
            "visible placeholder for HTML-without-alt, got: {result}"
        );
        assert!(
            !result.contains("raw html"),
            "raw HTML content must not leak into Typst output"
        );
    }

    #[test]
    fn test_md_to_typst_code_block() {
        let result = md_to_typst("```rust\nlet x = 1;\n```\n");
        assert!(result.contains("```rust"), "fenced code block preserved");
        assert!(result.contains("let x = 1;"), "code content preserved");
    }

    #[test]
    fn test_inline_code_with_backtick() {
        // Single backtick in content requires double-backtick delimiter in Typst.
        let result = md_to_typst("Use `` `tick` `` here.");
        assert!(
            result.contains("`` `tick` ``"),
            "double-backtick delimiter used"
        );
    }

    #[test]
    fn test_inline_code_plain() {
        let result = md_to_typst("Use `foo` here.");
        assert!(
            result.contains("`foo`"),
            "single-backtick for plain inline code"
        );
    }

    #[test]
    fn test_section_slide() {
        let mut talk = make_talk("Talk");
        let slide = Slide {
            kind: SlideKind::Part,
            title: Content::text("Part One"),
            ..Default::default()
        };
        talk.slides.push(slide);

        let bytes = generate_typst(&talk);
        let output = String::from_utf8(bytes).expect("utf8");

        assert!(output.contains("Part One"), "section title present");
    }

    #[test]
    fn test_part_slide_body_is_preserved() {
        // Regression: Part slides loaded from `_part.md` carry prose in body_source
        // (e.g. examples/riir-folder/02-success-stories/_part.md). The Typst section
        // writer was discarding the body — only the title was emitted.
        let mut talk = make_talk("Talk");
        let slide = Slide {
            kind: SlideKind::Part,
            title: Content::text("Success Stories"),
            body_source: Some("# Success Stories\n\nIntro prose for the part.".to_owned()),
            ..Default::default()
        };
        talk.slides.push(slide);

        let output = String::from_utf8(generate_typst(&talk)).expect("utf8");

        assert!(output.contains("Success Stories"), "part title present");
        assert!(
            output.contains("Intro prose for the part"),
            "part body preserved in Typst output"
        );
    }

    #[test]
    fn test_gfm_alert_note_renders_as_callout() {
        let result = md_to_typst("> [!NOTE]\n> Useful information.\n");
        assert!(
            result.contains("Useful information"),
            "alert body preserved"
        );
        assert!(
            result.contains("Note") || result.contains("NOTE") || result.contains("#info"),
            "NOTE label or info clue surfaced in Typst output, got: {result}"
        );
    }

    #[test]
    fn test_gfm_alert_tip_renders_as_callout() {
        let result = md_to_typst("> [!TIP]\n> Useful tip.\n");
        assert!(result.contains("Useful tip"), "tip body preserved");
        assert!(
            result.contains("Tip") || result.contains("TIP") || result.contains("#tip"),
            "TIP label or tip clue surfaced, got: {result}"
        );
    }

    #[test]
    fn test_gfm_alert_important_renders_as_callout() {
        let result = md_to_typst("> [!IMPORTANT]\n> Critical info.\n");
        assert!(result.contains("Critical info"), "important body preserved");
        assert!(
            result.contains("Important") || result.contains("IMPORTANT"),
            "IMPORTANT label surfaced, got: {result}"
        );
    }

    #[test]
    fn test_gfm_alert_warning_renders_as_callout() {
        let result = md_to_typst("> [!WARNING]\n> Beware.\n");
        assert!(result.contains("Beware"), "warning body preserved");
        assert!(
            result.contains("Warning") || result.contains("WARNING") || result.contains("#warning"),
            "WARNING label or warning clue surfaced, got: {result}"
        );
    }

    #[test]
    fn test_gfm_alert_caution_renders_as_callout() {
        let result = md_to_typst("> [!CAUTION]\n> Danger ahead.\n");
        assert!(result.contains("Danger ahead"), "caution body preserved");
        assert!(
            result.contains("Caution") || result.contains("CAUTION"),
            "CAUTION label surfaced, got: {result}"
        );
    }

    #[test]
    fn test_slide_with_style_classes_produces_content() {
        // Style classes are intentionally not rendered in Typst output.
        // Verify the slide body is still present even when classes are set.
        let mut talk = make_talk("Talk");
        let slide = Slide {
            kind: SlideKind::Standard,
            style: Style {
                classes: vec!["wide".to_owned()],
                style: None,
            },
            body_source: Some("# Styled\n\nContent.".to_owned()),
            ..Default::default()
        };
        talk.slides.push(slide);

        let output = String::from_utf8(generate_typst(&talk)).expect("utf8");
        assert!(
            output.contains("Content."),
            "slide body present despite style classes"
        );
        assert!(
            !output.contains("wide"),
            "style class not emitted in Typst output"
        );
    }
}
