use std::fmt::Write as _;

use comrak::nodes::{AstNode, ListType, NodeValue};
use comrak::{Arena, parse_document};
use toboggan_core::{Content, Slide, SlideKind, Talk};

use crate::parser::default_options;

pub(super) fn generate_typst(talk: &Talk) -> Vec<u8> {
    let mut out = String::new();
    write_preamble(&mut out, talk);
    for slide in &talk.slides {
        write_slide(&mut out, slide);
    }
    out.into_bytes()
}

fn write_preamble(out: &mut String, talk: &Talk) {
    let title = escape_typst(&talk.title);
    let date = talk.date.to_string();
    let _ = writeln!(
        out,
        r#"// Generated by toboggan-cli — compile with: typst compile presentation.typ

#set page(
  paper: "presentation-16-9",
  margin: (x: 2cm, y: 1.5cm),
)
#set text(size: 20pt)
#set heading(numbering: none)
#show heading.where(level: 1): it => block(below: 0.8em)[
  #text(size: 28pt, weight: "bold")[#it.body]
]

// ── Cover ──────────────────────────────────────────────────────────────────
#align(center + horizon)[
  #text(size: 36pt, weight: "bold")[{title}]
  #v(1em)
  #text(size: 20pt, fill: luma(120))[{date}]
]
#pagebreak()
"#
    );
}

fn write_slide(out: &mut String, slide: &Slide) {
    match slide.kind {
        SlideKind::Cover => {} // Cover is handled in write_preamble
        SlideKind::Part => write_section(out, slide),
        SlideKind::Standard => write_standard(out, slide),
    }
}

fn write_section(out: &mut String, slide: &Slide) {
    let title = content_to_typst_text(&slide.title);
    let _ = writeln!(
        out,
        r#"// ── Section ───────────────────────────────────────────────────────────────
#align(center + horizon)[
  #text(size: 30pt, weight: "semibold")[{title}]
]
#pagebreak()
"#
    );
}

fn write_standard(out: &mut String, slide: &Slide) {
    // Slides with live terminals that weren't filtered out get a placeholder.
    if slide.terminals.is_empty() {
        write_standard_body(out, slide);
    } else {
        write_terminal_placeholder(out, slide);
    }
}

fn write_terminal_placeholder(out: &mut String, slide: &Slide) {
    let title = content_to_typst_text(&slide.title);
    tracing::warn!(
        "Slide '{}' has live terminals but is not marked `hidden_in = [\"pdf\"]`. \
         Emitting placeholder in Typst output.",
        title
    );
    let _ = writeln!(
        out,
        r"// ── Slide (live terminal placeholder) ────────────────────────────────────
= {title}

#align(center + horizon)[
  #text(size: 1.2em, fill: luma(150))[\[Live terminal demo --- see recording / live presentation\]]
]

#pagebreak()
"
    );
}

fn write_standard_body(out: &mut String, slide: &Slide) {
    if slide.body_source.is_empty() {
        // Fallback for Talk files without body_source (e.g. pre-existing .toml files).
        let title = content_to_typst_text(&slide.title);
        let body = content_to_typst_body(&slide.body);
        let _ = writeln!(
            out,
            r"// ── Slide ────────────────────────────────────────────────────────────────
= {title}

{body}
#pagebreak()
"
        );
    } else {
        let body = md_to_typst(&slide.body_source);
        if body.trim().is_empty() {
            return;
        }
        let _ = writeln!(
            out,
            "// ── Slide ────────────────────────────────────────────────────────────────"
        );
        let _ = write!(out, "{body}");
        if !out.ends_with('\n') {
            out.push('\n');
        }
        let _ = writeln!(out, "#pagebreak()\n");
    }
}

/// Convert `Content` to a plain Typst text string (for titles).
fn content_to_typst_text(content: &Content) -> String {
    match content {
        Content::Empty => String::new(),
        Content::Text { text } => escape_typst(text),
        Content::Html { alt: Some(alt), .. } => escape_typst(alt),
        Content::Html { raw, .. } => escape_typst(&strip_html_tags(raw)),
    }
}

/// Convert `Content` to a Typst body block (best-effort for HTML fallback).
fn content_to_typst_body(content: &Content) -> String {
    match content {
        Content::Empty => String::new(),
        Content::Text { text } => escape_typst(text),
        Content::Html { alt: Some(alt), .. } => escape_typst(alt),
        Content::Html { raw, .. } => {
            // If there's no alt text, strip HTML tags as a best-effort fallback.
            escape_typst(&strip_html_tags(raw))
        }
    }
}

/// Strip HTML tags from a string.
fn strip_html_tags(html: &str) -> String {
    let mut out = String::with_capacity(html.len());
    let mut in_tag = false;
    for ch in html.chars() {
        match ch {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _ if !in_tag => out.push(ch),
            _ => {}
        }
    }
    out
}

/// Convert a `CommonMark` source string to Typst markup.
pub(super) fn md_to_typst(source: &str) -> String {
    let arena = Arena::new();
    let options = default_options();
    let root = parse_document(&arena, source, &options);
    let mut out = String::new();
    render_node(root, &mut out, 0, false);
    out
}

type MarkdownNode<'a> = AstNode<'a>;

fn render_children<'a>(
    node: &'a MarkdownNode<'a>,
    out: &mut String,
    list_depth: usize,
    tight: bool,
) {
    for child in node.children() {
        render_node(child, out, list_depth, tight);
    }
}

#[allow(clippy::too_many_lines)]
fn render_node<'a>(node: &'a MarkdownNode<'a>, out: &mut String, list_depth: usize, tight: bool) {
    match &node.data.borrow().value {
        NodeValue::FrontMatter(_) | NodeValue::HtmlBlock(_) | NodeValue::HtmlInline(_) => {
            // HTML blocks from slide sources are comment-marker artefacts
            // (<!-- term: ... -->, <!-- pause -->); already handled upstream.
        }

        NodeValue::Paragraph => {
            render_children(node, out, list_depth, tight);
            if tight {
                out.push('\n');
            } else {
                out.push_str("\n\n");
            }
        }

        NodeValue::Heading(heading) => {
            for _ in 0..heading.level {
                out.push('=');
            }
            out.push(' ');
            render_children(node, out, list_depth, tight);
            out.push('\n');
        }

        NodeValue::Text(text) => out.push_str(&escape_typst(text)),

        NodeValue::SoftBreak => out.push(' '),

        NodeValue::LineBreak => out.push_str("\\\n"),

        NodeValue::Strong => {
            out.push_str("#strong[");
            render_children(node, out, list_depth, tight);
            out.push(']');
        }

        NodeValue::Emph => {
            out.push_str("#emph[");
            render_children(node, out, list_depth, tight);
            out.push(']');
        }

        NodeValue::Strikethrough => {
            out.push_str("#strike[");
            render_children(node, out, list_depth, tight);
            out.push(']');
        }

        NodeValue::Code(code) => write_inline_code(out, &code.literal),

        NodeValue::CodeBlock(cb) => {
            let lang = cb.info.trim();
            write_fenced_code(out, lang, &cb.literal);
        }

        NodeValue::BlockQuote => {
            out.push_str("#quote(block: true)[\n");
            render_children(node, out, list_depth, tight);
            out.push_str("]\n\n");
        }

        NodeValue::ThematicBreak => out.push_str("#line(length: 100%)\n\n"),

        NodeValue::List(list) => {
            let is_ordered = list.list_type == ListType::Ordered;
            render_list(node, out, list_depth, is_ordered);
        }

        NodeValue::Item(_) => {
            let indent = "  ".repeat(list_depth.saturating_sub(1));
            out.push_str(&indent);
            out.push_str("- ");
            render_children(node, out, list_depth, true);
        }

        NodeValue::Link(link) => {
            let _ = write!(out, "#link(\"{url}\")[", url = link.url);
            render_children(node, out, list_depth, tight);
            out.push(']');
        }

        NodeValue::Image(link) => {
            let _ = writeln!(out, "#image(\"{}\")", link.url);
        }

        NodeValue::Table(_) => {
            render_table(node, out);
        }

        _ => render_children(node, out, list_depth, tight),
    }
}

fn render_list<'a>(node: &'a MarkdownNode<'a>, out: &mut String, depth: usize, ordered: bool) {
    for child in node.children() {
        let indent = "  ".repeat(depth);
        out.push_str(&indent);
        if ordered {
            out.push_str("+ ");
        } else {
            out.push_str("- ");
        }
        render_children(child, out, depth + 1, true);
    }
    out.push('\n');
}

fn render_table<'a>(node: &'a MarkdownNode<'a>, out: &mut String) {
    let mut rows: Vec<Vec<String>> = Vec::new();

    for row_node in node.children() {
        let mut cells: Vec<String> = Vec::new();
        for cell_node in row_node.children() {
            let mut cell = String::new();
            render_children(cell_node, &mut cell, 0, true);
            cells.push(cell.trim().to_owned());
        }
        rows.push(cells);
    }

    let Some(first) = rows.first() else { return };
    let columns = first.len();

    let _ = writeln!(out, "#table(");
    let _ = writeln!(out, "  columns: {columns},");
    for row in &rows {
        for cell in row {
            let _ = writeln!(out, "  [{cell}],");
        }
    }
    let _ = writeln!(out, ")\n");
}

/// Write an inline code span to `out`, using enough backticks to avoid
/// conflicts with any backtick sequences inside the literal.
fn write_inline_code(out: &mut String, code: &str) {
    let fence_len = max_consecutive_backticks(code) + 1;
    let fence = "`".repeat(fence_len);
    // When using multi-backtick delimiters, Typst requires a space before/after
    // the content if it would otherwise start or end with a backtick.
    let need_space = fence_len > 1 && (code.starts_with('`') || code.ends_with('`'));
    out.push_str(&fence);
    if need_space {
        out.push(' ');
    }
    out.push_str(code);
    if need_space {
        out.push(' ');
    }
    out.push_str(&fence);
}

/// Write a fenced code block to `out`, using enough backticks to avoid
/// conflicts with any backtick sequences inside the code.
fn write_fenced_code(out: &mut String, lang: &str, code: &str) {
    let fence_len = max_consecutive_backticks(code) + 3;
    let fence = "`".repeat(fence_len);
    let _ = write!(out, "{fence}{lang}\n{code}");
    if !code.ends_with('\n') {
        out.push('\n');
    }
    let _ = writeln!(out, "{fence}\n");
}

fn max_consecutive_backticks(src: &str) -> usize {
    let mut max = 0;
    let mut current = 0;
    for ch in src.chars() {
        if ch == '`' {
            current += 1;
            max = max.max(current);
        } else {
            current = 0;
        }
    }
    max
}

/// Escape Typst markup special characters with a backslash.
fn escape_typst(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '\\' | '*' | '_' | '`' | '#' | '@' | '<' | '>' | '[' | ']' | '{' | '}' | '$' | '~' => {
                out.push('\\');
                out.push(ch);
            }
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use toboggan_core::{Date, RenderTarget, Slide, SlideKind, Style, Talk, TerminalConfig};

    use super::*;

    fn make_talk(title: &str) -> Talk {
        let mut talk = Talk::new(title);
        talk.date = Date::new(2024, 1, 15).expect("valid date");
        talk
    }

    #[test]
    fn test_cover_slide_preamble() {
        let talk = make_talk("My Presentation");
        let bytes = generate_typst(&talk);
        let output = String::from_utf8(bytes).expect("utf8");

        assert!(output.contains("My Presentation"), "title in preamble");
        assert!(output.contains("2024-01-15"), "date in preamble");
        assert!(output.contains("#set page"), "page setup present");
        assert!(output.contains("#pagebreak()"), "pagebreak after cover");
    }

    #[test]
    fn test_standard_slide_with_code_block() {
        let mut talk = make_talk("Code Talk");
        let source = "# Demo\n\n```rust\nfn main() {}\n```\n";
        let slide = Slide {
            kind: SlideKind::Standard,
            title: Content::text("Demo"),
            body_source: source.to_owned(),
            ..Default::default()
        };
        talk.slides.push(slide);

        let bytes = generate_typst(&talk);
        let output = String::from_utf8(bytes).expect("utf8");

        assert!(output.contains("```rust"), "fenced code block");
        assert!(output.contains("fn main()"), "code content");
    }

    #[test]
    fn test_slide_with_terminals_emits_placeholder() {
        let mut talk = make_talk("Demo Talk");
        let slide = Slide {
            kind: SlideKind::Standard,
            title: Content::text("Live Demo"),
            terminals: vec![TerminalConfig::new(".")],
            ..Default::default()
        };
        talk.slides.push(slide);

        let bytes = generate_typst(&talk);
        let output = String::from_utf8(bytes).expect("utf8");

        assert!(
            output.contains("Live terminal demo"),
            "placeholder present for unmarked live slide"
        );
    }

    #[test]
    fn test_hidden_in_pdf_slide_is_omitted() {
        let mut talk = make_talk("Demo Talk");
        let live_slide = Slide {
            kind: SlideKind::Standard,
            title: Content::text("Live Demo"),
            terminals: vec![TerminalConfig::new(".")],
            hidden_in: vec![RenderTarget::Pdf],
            ..Default::default()
        };
        let static_slide = Slide {
            kind: SlideKind::Standard,
            title: Content::text("Static Demo"),
            body_source: "# Static Demo\n\n```rust\nfn main() {}\n```\n".to_owned(),
            hidden_in: vec![RenderTarget::Web],
            ..Default::default()
        };
        talk.slides.push(live_slide);
        talk.slides.push(static_slide);

        // Simulate the filter that serialize_talk applies before calling generate_typst.
        let filtered_slides: Vec<_> = talk
            .slides
            .iter()
            .filter(|slide| !slide.hidden_in.contains(&RenderTarget::Pdf))
            .cloned()
            .collect();
        let mut filtered_talk = talk.clone();
        filtered_talk.slides = filtered_slides;

        let bytes = generate_typst(&filtered_talk);
        let output = String::from_utf8(bytes).expect("utf8");

        assert!(
            !output.contains("Live Demo"),
            "pdf-hidden live slide must be absent"
        );
        assert!(
            output.contains("Static Demo"),
            "web-hidden static slide must be present"
        );
    }

    #[test]
    fn test_escape_typst() {
        assert_eq!(escape_typst("hello"), "hello");
        assert_eq!(escape_typst("a#b"), r"a\#b");
        assert_eq!(escape_typst("x[y]"), r"x\[y\]");
        assert_eq!(escape_typst("a*b_c"), r"a\*b\_c");
    }

    #[test]
    fn test_md_to_typst_heading() {
        let result = md_to_typst("# Title\n\nParagraph.");
        assert!(result.contains("= Title"), "h1 → = Title");
        assert!(result.contains("Paragraph"), "paragraph preserved");
    }

    #[test]
    fn test_md_to_typst_code_block() {
        let result = md_to_typst("```rust\nlet x = 1;\n```\n");
        assert!(result.contains("```rust"), "fenced code block preserved");
        assert!(result.contains("let x = 1;"), "code content preserved");
    }

    #[test]
    fn test_inline_code_with_backtick() {
        // Single backtick in content requires double-backtick delimiter in Typst.
        let result = md_to_typst("Use `` `tick` `` here.");
        assert!(result.contains("`` `tick` ``"), "double-backtick delimiter used");
    }

    #[test]
    fn test_inline_code_plain() {
        let result = md_to_typst("Use `foo` here.");
        assert!(result.contains("`foo`"), "single-backtick for plain inline code");
    }

    #[test]
    fn test_section_slide() {
        let mut talk = make_talk("Talk");
        let slide = Slide {
            kind: SlideKind::Part,
            title: Content::text("Part One"),
            ..Default::default()
        };
        talk.slides.push(slide);

        let bytes = generate_typst(&talk);
        let output = String::from_utf8(bytes).expect("utf8");

        assert!(output.contains("Part One"), "section title present");
    }

    #[test]
    fn test_slide_with_style_classes() {
        let mut talk = make_talk("Talk");
        let slide = Slide {
            kind: SlideKind::Standard,
            title: Content::text("Styled"),
            style: Style {
                classes: vec!["wide".to_owned()],
                style: None,
            },
            body_source: "# Styled\n\nContent.".to_owned(),
            ..Default::default()
        };
        talk.slides.push(slide);

        let bytes = generate_typst(&talk);
        assert!(
            !bytes.is_empty(),
            "output non-empty for slide with style classes"
        );
    }
}
